{"name": "test_tc_004_Transaction_withrraw", "status": "failed", "statusDetails": {"message": "AssertionError: assert True == False", "trace": "def test_tc_004_Transaction_withrraw():\n        print('This is my test case code...')\n        print('Test case is finished ...')\n>       assert actual_result == False\nE       assert True == False\n\nAutomationCases\\test_TC_004_Forth_Test_case.py:24: AssertionError"}, "attachments": [{"name": "stdout", "source": "5e589ba7-ce66-4511-a57a-b7d62caa54ea-attachment.txt", "type": "text/plain"}], "start": 1674489872628, "stop": 1674489872629, "uuid": "731416bc-92cf-4683-9d5b-ffb2a45d28f3", "historyId": "07679b4d9782194eb628b9700baef10b", "testCaseId": "bd64037dd2b91074f7c01e0886b4e505", "fullName": "test_TC_004_Forth_Test_case#test_tc_004_Transaction_withrraw", "labels": [{"name": "suite", "value": "test_TC_004_Forth_Test_case"}, {"name": "host", "value": "__VK__"}, {"name": "thread", "value": "3560-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_TC_004_Forth_Test_case"}]}