{"name": "test_tc_004_Transaction_withrraw", "status": "failed", "statusDetails": {"message": "AssertionError: assert True == False", "trace": "def test_tc_004_Transaction_withrraw():\n        print('This is my test case code...')\n        print('Test case is finished ...')\n>       assert actual_result == False\nE       assert True == False\n\nAutomationCases\\test_TC_004_Forth_Test_case.py:24: AssertionError"}, "attachments": [{"name": "stdout", "source": "edd48db5-ec65-44eb-8a9d-1bd53c1d5536-attachment.txt", "type": "text/plain"}], "start": 1674490125626, "stop": 1674490125626, "uuid": "11edd328-dc95-479e-a321-ddbf9b81909c", "historyId": "07679b4d9782194eb628b9700baef10b", "testCaseId": "bd64037dd2b91074f7c01e0886b4e505", "fullName": "test_TC_004_Forth_Test_case#test_tc_004_Transaction_withrraw", "labels": [{"name": "suite", "value": "test_TC_004_Forth_Test_case"}, {"name": "host", "value": "__VK__"}, {"name": "thread", "value": "24868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_TC_004_Forth_Test_case"}]}